config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #get '/calculadora', to: 'calculator#math'

  get '/formulario', to: 'contact#form', as: :my_form
  get '/destino', to: 'contact#destiny', as: :destiny
  
  post '/destino', to: 'contact#destiny', as: :post_destiny
  get '/fim', to: 'contact#final', as: :final

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def form
    end
    def destiny
        redirect_to final_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/_myform.html.erb
<h2>Poggers, <%= name %></h2>

<%= form_with url: post_destiny_path, class: "form" do |f|%>
    
    <p>Name:</p>
    <%= f.text_field :name %>
    <p>Email:</p>
    <%= f.text_field :email %>
    <p>Mensagem</p>
    <%= f.text_area :mensagem %>
    <%= f.submit "Enviar"%>

<% end %>

app/views/contact/final.html.erb
<h1>Final</h1>
<%= :name %>

app/views/contact/form.html.erb
<h1>Formulário</h1>
<%= render 'myform', name: "Chat" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>